spring:
  application:
    name: user-crud
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb?currentSchema=appdb
    username: appuser
    password: appuser
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: appdb
server:
  port: 8080
