name: Deploy to EC2 Tomcat

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & Rename
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: |
          mvn clean package -DskipTests
          mv target/*.war target/ROOT.war

      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/ROOT.war"
          target: "/home/ubuntu"
          strip_components: 1

      - name: Finalize Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /opt/tomcat/webapps/ROOT*
            sudo mv /home/ubuntu/ROOT.war /opt/tomcat/webapps/
            sudo chown tomcat:tomcat /opt/tomcat/webapps/ROOT.war
            sudo systemctl restart tomcat